<template>
  <div class="report-footer">
    <div class="footer-content">
      <div class="footer-info">
        <h3>分析说明</h3>
        <ul>
          <li>1. 数据来源：本报告数据基于实时隐患排查治理系统数据生成。</li>
          <li>2. 统计范围：仅包含已审核入库的有效隐患数据。</li>
          <li>3. 更新频次：数据实时更新，图表展示可能存在分钟级延迟。</li>
          <li>4. 风险提示：数据仅供参考，具体隐患处置请以现场实际情况为准。</li>
        </ul>
      </div>
      <div class="footer-copyright">
        <p>Copyright © {{ new Date().getFullYear() }} 安全隐患排查治理系统</p>
        <p>Generated by Intelligent Analysis Engine</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.report-footer {
  margin-top: 48px;
  padding: 48px 24px;
  background: #f0f2f5;
  border-top: 1px solid #e8e8e8;
  text-align: center;
}

.footer-content {
  max-width: 800px;
  margin: 0 auto;
}

.footer-info {
  text-align: left;
  margin-bottom: 32px;
  padding: 24px;
  background: #fff;
  border-radius: 8px;
  box-shadow: 0 1px 2px rgba(0, 0, 0, 0.03);
}

.footer-info h3 {
  font-size: 16px;
  font-weight: 600;
  color: #262626;
  margin-bottom: 16px;
  padding-left: 12px;
  border-left: 4px solid #1890ff;
}

.footer-info ul {
  list-style: none;
  padding: 0;
  margin: 0;
}

.footer-info li {
  font-size: 14px;
  color: rgba(0, 0, 0, 0.65);
  margin-bottom: 8px;
  line-height: 1.8;
}

.footer-copyright {
  color: rgba(0, 0, 0, 0.45);
  font-size: 14px;
}

.footer-copyright p {
  margin-bottom: 8px;
}
</style>
